// 3270. Find the Key of the Numbers
// Solved
// Easy
// Topics
// premium lock icon
// Companies
// You are given three positive integers num1, num2, and num3.

// The key of num1, num2, and num3 is defined as a four-digit number such that:

// Initially, if any number has less than four digits, it is padded with leading zeros.
// The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
// Return the key of the three numbers without leading zeros (if any).

 

// Example 1:

// Input: num1 = 1, num2 = 10, num3 = 1000

// Output: 0

// Explanation:

// On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".

// The 1st digit of the key is min(0, 0, 1).
// The 2nd digit of the key is min(0, 0, 0).
// The 3rd digit of the key is min(0, 1, 0).
// The 4th digit of the key is min(1, 0, 0).
// Hence, the key is "0000", i.e. 0.

// Example 2:

// Input: num1 = 987, num2 = 879, num3 = 798

// Output: 777

// Example 3:

// Input: num1 = 1, num2 = 2, num3 = 3

// Output: 1

 

// Constraints:

// 1 <= num1, num2, num3 <= 9999

class Solution {
    public int generateKey(int num1, int num2, int num3) {
       int value=1;
       int ans=0;
       for(int i=0;i<4;i++){  //four loop for this will take like this 0001,0010
        int d1=num1%10;
        int d2=num2%10;
        int d3=num3%10; //extract last digit 987->7

        int min=Math.min(d1,Math.min (d2,d3));  // min 7
       ans=ans+min*value;  // 0=0+7*1=7
        num1/=10;   //remainig two number 98
        num2/=10;   //remainig two number 87
        num3/=10;   // remainig two number 79
        value=value*10;     //1=1*10->10
       }//after 4 loop ans 777
       return ans; //return that ans
    }
}